#include "ws2812b.h"
#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "math.h"

// .h file generated by CMake
#include "ws2812b.pio.h"

static inline void put_pixel(PIO pio, uint sm, uint32_t pixel_grb) {
    pio_sm_put_blocking(pio, sm, pixel_grb << 8u);
}

static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return
            ((uint32_t) (r) << 16u ) |
            ((uint32_t) (g) << 24u ) |
            ((uint32_t) (b) << 8u  );
  }

void setPattern() {
    PIO pio;
    uint sm;
    uint offset;

    bool success = pio_claim_free_sm_and_add_program_for_gpio_range(&ws2812b_program, &pio, &sm, &offset, WS2812B_PIN, 1, true);
    hard_assert(success);

    ws2812b_program_init(pio, sm, offset, WS2812B_PIN, 800000);

    put_pixel(pio, sm, urgb_u32(255, 0, 0));
}
